In [1]:
import streamlit as st
import streamlit_antd_components as sac
import pandas as pd
import time
from streamlit_gsheets import GSheetsConnection
import base64
from io import BytesIO
from PIL import Image
import requests
import numpy as np

2025-03-12 10:16:18.571 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [2]:
conn = st.connection("gsheets", type=GSheetsConnection)
df = conn.read(worksheet="DATA", ttl=10)
df = df.dropna(thresh=2)
df = df.sort_values(by="INCENTIVE", ascending=False).reset_index(drop=True)

selected_departments = ['INTERIOR', 'WELDER', 'FRMAE', 'FABRIC', 'SEWING', 'SPONGE', 'SPRAY', 'PACKING', 'ASSEMBLY', 'OUTDOOR']
df = df[df['DEPARTMENT'].isin(selected_departments)]

2025-03-12 10:16:44.372 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:44.611
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\MyPc\anaconda3\envs\stenv\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-03-12 10:16:44.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:44.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:45.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:45.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:45.081 No runtime found, using MemoryCacheStorageManager
2025-03-12 10:16:45.087 No runtime found, using MemoryCacheStorageManager
2025-03-12 10:16:45.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:45.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:45.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:45.595 Thread 'Thread-6': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:45.601 Thread 'Thread-6': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:46.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 10:16:46.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [3]:
df

,DEPARTMENT,STAFF NAME,PICTURE,INCENTIVE
4,ASSEMBLY,ABDUL RAHMAN BIN DZULKIFLI,https://drive.google.com/file/d/1llT1jJTdk53MO...,400.0
6,SPRAY,WATI BINTI ABU SAMAH,https://drive.google.com/file/d/1GXtl2tf0TwMX_...,300.0
7,ASSEMBLY,KHUN HLA NAY,https://drive.google.com/file/d/1JLE1SKKz_aBD4...,300.0
8,ASSEMBLY,DIL BAHADUR RASKOTI,https://drive.google.com/file/d/1-khBfAI7F4Wch...,300.0
9,ASSEMBLY,SHYAM BAHADUR,https://drive.google.com/file/d/1ViQW2aUQnK21B...,300.0
10,ASSEMBLY,HAFIZI BIN IZHAR,https://drive.google.com/file/d/11M1BUq9PCumB9...,300.0
11,SPRAY,KHAIRUL NIZAM BIN MOHD ALI,NaN,300.0
12,ASSEMBLY,AHMED NADEEM,https://drive.google.com/file/d/1n313Z70QhP4Bu...,300.0
13,SPRAY,WAZE BINTI ABU SAMAH,https://drive.google.com/file/d/1QX0R-neGBqoPk...,300.0
14,SPRAY,KYAW LWIN,https://drive.google.com/file/d/1V1R93LJ5_ujdP...,300.0
17,PACKING,MUHAMAD BADRUL HISYAM BIN CHE KAH,https://drive.google.com/file/d/1nz0I0JQQMbi8b...,300.0
18,SPRAY,ABDUL GHAFFAR,https://drive.google.com/file/d/1NKxtTNJ02zY_U...,300.0
19,SPRAY,MAN BAHADUR UCHAI,https://drive.google.com/file/d/1lJ-j2BD467f28...,300.0
20,SPONGE,MUHAMMAD HAZIQ BIN AL ROHAIDIL,https://drive.google.com/file/d/1qpxBnMFElSutk...,300.0
21,SPONGE,ABDUL WAHAB BIN NORSAH,https://drive.google.com/file/d/1Ch2f62SdBuO5_...,300.0
22,SPONGE,MUHAMMAD FIRDAUS BIN BAHARUDDIN,https://drive.google.com/file/d/1malmEnhtO1bkb...,300.0
23,SPONGE,ARJUN KSEDAL,https://drive.google.com/file/d/1V54qUDMWG625q...,300.0
24,SPRAY,MUHAMMAD FITRI BIN ABD JALIL,https://drive.google.com/file/d/1wSIF_cdYImTpE...,300.0
25,SEWING,TEY SIEW SANG,https://drive.google.com/file/d/1nxIyHm0FeHrl3...,300.0
26,PACKING,PYONE CHO,https://drive.google.com/file/d/1MRmg1pNpSVXmg...,300.0
37,SEWING,SATTI SARFARAZ NAWAZ,https://drive.google.com/file/d/10Db6ptBW6dS7v...,300.0
41,WELDER,FARID FARHAN BIN MOHAMED HANAPIAH,NaN,300.0
42,PACKING,NOR HAKIMI BIN JALI,https://drive.google.com/file/d/1gfZYZqCqRNmyJ...,300.0
44,PACKING,AHMAD ASROL BIN AHMAD RIZAL,https://drive.google.com/file/d/1MfJEIvdUrMmNb...,300.0
45,ASSEMBLY,ALFIKRY BIN AZMAN,NaN,300.0
46,SPONGE,A'AMIRUL ASHYRAFF BIN MOHD ZAIRUS,NaN,300.0
48,SEWING,MAZRIATY SYAHANA BINTI MAZLAN,https://drive.google.com/file/d/1jop2bqYItKpHj...,300.0
49,WELDER,NIK MUHAMMAD HAKIMIE BIN NIKPA,NaN,300.0
57,SEWING,MANONMANI A/P FRANCIS,https://drive.google.com/file/d/1oPPg-F3_nqk9n...,300.0
58,OUTDOOR,CHULHAI MAJHI MU,https://drive.google.com/file/d/1o1d0zQZNI8hlA...,300.0
59,OUTDOOR,NANTU DAS,https://drive.google.com/file/d/1tJVKCgZB41fmh...,300.0
60,OUTDOOR,MUHAMMAD AIDIL BIN KADUK,https://drive.google.com/file/d/1ed61gu46DrCLJ...,300.0
63,ASSEMBLY,MOHAMMAD SYALAHUDDIN BAIE,https://drive.google.com/file/d/1EMXTKFxSVjzrs...,300.0
67,FABRIC,SHAHRULNIZAM BIN ZAMANI,https://drive.google.com/file/d/1RnO2tA5_dvwg-...,300.0
68,SEWING,BIRENDRA KUMAR CHEDAL,https://drive.google.com/file/d/1U8voTP60QQPRL...,300.0
69,SEWING,SITI NORAFIDAH BINTI ABDUL WAHAB,https://drive.google.com/file/d/1cP18PHOYdsYXB...,300.0
70,FABRIC,FAISAL BIN ABU BAKAR,https://drive.google.com/file/d/1zFdyrovm6MDo5...,300.0
71,SEWING,NORHAMIDAH BINTI ABU KASIM,https://drive.google.com/file/d/1IdBuByqvMbFXc...,300.0
72,SEWING,FONG AH MOY,https://drive.google.com/file/d/1Eyh_YJ_83yAC3...,300.0
73,SEWING,SITI UMMIRA BINTI ABDULLAH,https://drive.google.com/file/d/1_dwWHh-opAOHX...,300.0
74,INTERIOR,AFIQ FIRDAUS BIN MD SUFFIAN,https://drive.google.com/file/d/1S87KWaKY-8Eqy...,300.0
75,ASSEMBLY,MUHAMMAD SHUKRI BIN YUSOF,https://drive.google.com/file/d/1UXZsd-5pElnI0...,300.0
76,INTERIOR,DHIRAJ NEPALI,https://drive.google.com/file/d/12yaybuB9-78sH...,300.0
77,INTERIOR,PATHIK AMRIKA PRASAD,https://drive.google.com/file/d/1HXAEUId_JuwP_...,300.0
78,INTERIOR,NOMAN MUHAMMAD,https://drive.google.com/file/d/18jFNBqM7dbTwq...,300.0
79,INTERIOR,TARA BAHADUR,https://drive.google.com/file/d/1qiNju7RoiRAiA...,300.0
80,INTERIOR,LEE HENG HAU,https://drive.google.com/file/d/1_YoltDEwk-_2o...,300.0
81,INTERIOR,YONG KAH LOONG,https://drive.google.com/file/d/1653iMbDhP_-Wv...,300.0
83,INTERIOR,NUR MUSTAQIM BIN ISMAIL,NaN,300.0
87,FABRIC,USMAN AHMED,https://drive.google.com/file/d/1PCXOfwVQljciY...,300.0
90,SEWING,HAIBAH MASYITAH BINTI MESENO,NaN,NaN
91,SPRAY,MUHAMAD ARMANI MIRZA BIN SAUPI,NaN,NaN

In [69]:
department_table = pd.pivot_table(df, values='INCENTIVE', index=['DEPARTMENT'], aggfunc=np.sum)
department_table

C:\Users\MyPc\AppData\Local\Temp\ipykernel_12992\514693865.py:1: FutureWarning: The provided callable <function sum at 0x0000015649A52E50> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  department_table = pd.pivot_table(df, values='INCENTIVE', index=['DEPARTMENT'], aggfunc=np.sum)

            INCENTIVE
DEPARTMENT
ASSEMBLY       2800.0
FABRIC          900.0
INTERIOR       2400.0
OUTDOOR         900.0
PACKING        1200.0
SEWING         2700.0
SPONGE         1500.0
SPRAY          2100.0
WELDER          600.0

In [59]:
staff_table = pd.pivot_table(df, values='STAFF NAME', index=['DEPARTMENT'], aggfunc="count")
staff_table = staff_table.rename(columns={"STAFF NAME": "STAFF COUNT"})
staff_table

            STAFF COUNT
DEPARTMENT
ASSEMBLY              9
FABRIC                3
INTERIOR              8
OUTDOOR               3
PACKING               4
SEWING               10
SPONGE                5
SPRAY                 8
WELDER                2

In [28]:
for x in range(3):
    print(department_table.iloc[x])

INCENTIVE    2800.0
Name: ASSEMBLY, dtype: float64
INCENTIVE    2700.0
Name: SEWING, dtype: float64
INCENTIVE    2400.0
Name: INTERIOR, dtype: float64

In [62]:
staff_ranking_table = department_table.merge(staff_table, on="DEPARTMENT", how="outer").fillna(0).sort_values(by=['INCENTIVE'], ascending=False)
staff_ranking_table

            INCENTIVE  STAFF COUNT
DEPARTMENT
ASSEMBLY       2800.0            9
SEWING         2700.0           10
INTERIOR       2400.0            8
SPRAY          2100.0            8
SPONGE         1500.0            5
PACKING        1200.0            4
FABRIC          900.0            3
OUTDOOR         900.0            3
WELDER          600.0            2

In [107]:
staff_ranking_table["Avg Incentive per Staff"] = staff_ranking_table["INCENTIVE"] / staff_ranking_table["STAFF COUNT"]
total_avg_incentive = staff_ranking_table["Avg Incentive per Staff"].sum()
staff_ranking_table["Fair Incentive Percentage"] = (staff_ranking_table["Avg Incentive per Staff"] / total_avg_incentive) * 100
staff_ranking_table = staff_ranking_table.sort_values(by=['Fair Incentive Percentage'], ascending=False)
staff_ranking_table

,INCENTIVE,STAFF COUNT,Avg Incentive Per Staff,Avg Incentive per Staff,Fair Incentive Percentage
DEPARTMENT,,,,,
ASSEMBLY,2800.0,9,311.111111,311.111111,11.768414
INTERIOR,2400.0,8,300.000000,300.000000,11.348114
SPONGE,1500.0,5,300.000000,300.000000,11.348114
PACKING,1200.0,4,300.000000,300.000000,11.348114
FABRIC,900.0,3,300.000000,300.000000,11.348114
OUTDOOR,900.0,3,300.000000,300.000000,11.348114
WELDER,600.0,2,300.000000,300.000000,11.348114
SEWING,2700.0,10,270.000000,270.000000,10.213303
SPRAY,2100.0,8,262.500000,262.500000,9.929600

In [105]:
for x in range(3):
    print(staff_ranking_table.iloc[x, 0])
    # print(staff_ranking_table.iloc[x][0])
    # print(staff_ranking_table.iloc[x][-1])
    print(staff_ranking_table.index[x])

2800.0
ASSEMBLY
2400.0
INTERIOR
1500.0
SPONGE

In [122]:
staff_image = df[df['DEPARTMENT'] == staff_ranking_table.index[2]]
image_data = staff_image.iloc[x]["PICTURE"]

def get_image_url(url):
    """Convert Google Drive link to a direct image URL."""
    if isinstance(url, str) and "drive.google.com" in url:
        if "/file/d/" in url:
            file_id = url.split("/d/")[1].split("/")[0]
            return requests.get(f"https://drive.google.com/uc?export=view&id={file_id}").content
        elif "id=" in url:
            file_id = url.split("id=")[1]
            return requests.get(f"https://drive.google.com/uc?export=view&id={file_id}").content
    return url  # Return the original URL if it's not from Google Drive

def decode_image(base64_string):
    """Convert Base64 string to an image, handling errors safely."""
    try:
        base64_string = base64_string.strip()
        image_bytes = base64.b64decode(base64_string)
        return Image.open(BytesIO(image_bytes))
    except Exception:
        return None

# Display Image
if pd.isna(image_data) or image_data.strip() == "":
    st.write("🚫 No Image Available")
elif image_data.startswith("http"):
    st.image(get_image_url(image_data), width=400)
else:
    image = decode_image(image_data)
    st.image(image, width=300) if image else st.write("🚫 No Image Available")

2025-03-12 12:34:38.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 12:34:38.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-03-12 12:34:38.312 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [124]:
len(staff_image)

5